# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='data',
            field=models.CharField(default=datetime.datetime(2016, 3, 15, 9, 20, 21, 362333, tzinfo=utc), max_length=5000),
            preserve_default=False,
        ),
    ]
